version: "{build}"
skip_non_tags: true
environment:
  NuGetApiKey:
    secure: 23+pfmN1D6MWK5DKZNxxX1R3VxBJ/Dn8/wVzJWqV7RvJcBoffGEx96hfa/fPOHyW
install:
  - ps: Install-Module psake, Pester
build: false
test_script:
  - ps: |-
      Invoke-psake -buildFile ./psakefile.ps1 -taskList Test -nologo -notr

      if (-not $psake.build_success) {
        exit 1
      }
artifacts:
  - path: Module
    name: $(APPVEYOR_PROJECT_NAME)
before_deploy:
  - ps: Invoke-psake -buildFile ./psakefile.ps1 -taskList InitializeDeployments -nologo -notr
deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    description: $(RELEASE_DESCRIPTION)
    auth_token:
      secure: +PxazkcvZpF9LLVySBX9zHY5O8hIWpW0+6AGd7j3uX747Sl8hyIqHMgpBiAC4WpYa8hjCJI6KTzYdDD+G7iczS7UGspTj+UzK9708fNYLcET3pe/bvndYzg4UKbW9k4L
    artifact: $(APPVEYOR_PROJECT_NAME)
    prerelease: $(IS_PRERELEASE)
    on:
      APPVEYOR_REPO_TAG: true
after_deploy:
  - ps: |-
      Invoke-psake -buildFile ./psakefile.ps1 -taskList DeployToPowerShellGallery -nologo -notr

      if (-not $psake.build_success) {
        exit 1
      }
# on_finish:
#   # Upload test results on build finish (after_test will not run on a failed build)
#   - ps: |-
#       # Upload test results to AppVeyor
#       $client = [System.Net.WebClient]::new()
#       $results = Resolve-Path (Join-Path 'TestResults' 'testResults.xml')
#       $client.UploadFile("$env:APPVEYOR_URL/api/testresults/nunit3/$env:APPVEYOR_JOB_ID", $results)
